version: '3'
services:
  bms_postgres:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_DB: bms_db
      POSTGRES_USER: bms_user
      POSTGRES_PASSWORD: bms_password
      PGDATA: /var/lib/postgresql/data/some_name
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ./db:/var/lib/postgresql/data/some_name/

  bms_flyway:
    image: flyway/flyway:latest
    container_name: ${FLYWAY_CONTAINER_NAME}
    command: ["migrate","info"]
    environment:
      - FLYWAY_URL=jdbc:postgresql://bms_postgres:5432/bms_db
      - FLYWAY_USER=bms_user
      - FLYWAY_PASSWORD=bms_password
    volumes:
      - ./flyway-migration/sql:/flyway/sql
    depends_on:
      - bms_postgres
    stdin_open: true
    tty: true  

  bms_listing_service:
    build:
      context: ./feature/listing
      dockerfile: Dockerfile
      args:
        - IMAGE_NAME=listing_feature_backend_image
    container_name: ${LISTING_FEATURE_BACKEND_CONTAINER_NAME}
    ports:
      - "8090:8080"
    depends_on:
      - bms_postgres

