version: '3'
services:
  bms_postgres:
    image: postgres:latest
    container_name: bms-postgres-container
    environment:
      POSTGRES_DB: bms_db
      POSTGRES_USER: bms_user
      POSTGRES_PASSWORD: bms_password
    ports:
      - "5432:5432"

  bms_flyway:
    image: flyway/flyway:latest
    container_name: bms-flyway-container
    command: ["migrate"]
    environment:
      - FLYWAY_URL=jdbc:postgresql://bms_postgres:5432/bms_db
      - FLYWAY_USER=bms_user
      - FLYWAY_PASSWORD=bms_password
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - bms_postgres
