version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: bms-postgres-container
    environment:
      POSTGRES_USER: bms_user
      POSTGRES_PASSWORD: bms_password
      POSTGRES_DB: bms_db
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
