# Stage 1: Build the Go application
FROM golang:latest AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

# Install oapi-codegen
RUN go get github.com/deepmap/oapi-codegen/cmd/oapi-codegen

COPY ./openapi/openapi.yaml ./openapi/
RUN find . -type d

# Build the Go application into a binary
COPY . .
RUN go build -o /app/book_anish_show ./cmd/main.go

# Stage 2: Create the final lightweight image
FROM golang:latest

WORKDIR /app

# Copy the binary from the builder stage
COPY --from=builder /app/book_anish_show ./book_anish_show

# Expose the port your application will listen on
EXPOSE 8080

# Command to run your Go application
CMD ["./book_anish_show"]
